name = "casa-benavides"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist/public"

[build]
command = "npm run build"
cwd = "."
watch_dir = "."

[vars]
NODE_VERSION = "20"